[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = ["dotnet restore", "dotnet publish HospitadentApi.WebService/HospitadentApi.WebService.csproj -c Release -o /app/out"]

[phases.start]
cmd = "dotnet /app/out/HospitadentApi.WebService.dll"

