[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet publish HospitadentApi.WebService/HospitadentApi.WebService.csproj -c Release -o out"]

[phases.start]
cmd = "dotnet out/HospitadentApi.WebService.dll"

